jflanakin@cloudshell:~ (neat-height-303119)$ gcloud compute disks create kubernetes-disk --project=neat-height-303119 --type=pd-balanced --description=Disk\ for\ kubernetes --size=10GB --zone=us-central1-a
Created [https://www.googleapis.com/compute/v1/projects/neat-height-303119/zones/us-central1-a/disks/kubernetes-disk].
NAME: kubernetes-disk
ZONE: us-central1-a
SIZE_GB: 10
TYPE: pd-balanced
STATUS: READY

New disks are unformatted. You must format and mount a disk before it
can be used. You can find instructions on how to do this at:

https://cloud.google.com/compute/docs/disks/add-persistent-disk#formatting

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: jamf-pro
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: jamf-pro
    name: mysql-volume
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/neat-height-303119/regions/us-central1/disks/gce-disk-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jamf-pro
  name: mysql-volume
spec:
  storageClassName: "manual"
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi