# Deploy service to allow connections to Jamf Pro pods externally
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: jamf-pro
  labels:
    app: jamf-pro
spec:
  type: NodePort
  ports:
  - name: "https"
    nodePort: 31621
    targetPort: 8080
    protocol: TCP
  selector:
    app: jamf-pro